custom: [ "https://send.monobank.ua/jar/6nFMUQaJtQ?f=enabled&t=uacashbackbot", "https://mobile-app.pumb.ua/JLPrqZcqwdxBmsG56", "https://www.privat24.ua/send/dd4x5", "https://www.paypal.com/donate/?hosted_button_id=TVBTVSBF89SQE" ]
