blank_issues_enabled: true
contact_links:
  - name: Questions and suggestions
    url: 'https://t.me/vitalij_r2'
    about: |
      Jakščo u vas je pytannja čy propozyciji možete napysaty
      meni prjamo v Telegram | If you have questions
      or suggestions, you can write to me directly in
      Telegram | Якщо у вас є питання чи пропозиції можете
      написати мені прямо в Телеграм
