blank_issues_enabled: true
contact_links:
  - name: Pytannja ta propozyciji
    url: https://t.me/vitalij_r2
    about: |
      Jakščo u vas je pytannja čy propozyciji možete napysaty meni
      prjamo v Telegram
